"""Generate static/css/icons.css: the Font Awesome Free (CC BY 4.0 icons) glyphs this app uses,
as CSS-mask data URIs, so pages need no icon webfont (about 150 KB) and no CDN.

Usage:  python scripts/build_icons.py /path/to/@fortawesome/fontawesome-free   (npm package dir)
Add a name to ICONS below (use the classic FA class name, e.g. 'trash-alt'), rerun, commit the CSS.
"""
import json
import re
import sys
from pathlib import Path
from urllib.parse import quote

ICONS = """
arrow-down arrow-left arrow-right arrow-up book check check-circle check-double clock cog copy download
ellipsis-h exclamation-circle exclamation-triangle file-import folder folder-open folder-tree headphones
info-circle key link list lock moon pause play plus redo save search sign-in-alt sliders-h sun sync sync-alt
th-large times times-circle trash trash-alt user-circle user-plus users
""".split()


def main(pkg: Path, out: Path) -> None:
    # metadata/icons.yml: top-level "<canonical>:" blocks, each with an optional "aliases: names: [- x]" list
    canonical_of, current, in_names = {}, None, False
    for line in (pkg / "metadata" / "icons.yml").read_text().splitlines():
        m = re.match(r"^([a-z0-9-]+):\s*$", line)
        if m:
            current, in_names = m.group(1), False
            canonical_of[current] = current
        elif current and re.match(r"^    names:\s*$", line):
            in_names = True
        elif in_names and (m := re.match(r"^      - ([a-z0-9-]+)\s*$", line)):
            canonical_of[m.group(1)] = current
        elif in_names and not line.startswith("      - "):
            in_names = False
    groups = {n: [c] for n, c in canonical_of.items()}
    rules, missing = [], []
    for name in ICONS:
        svg_path = next((pkg / "svgs" / "solid" / f"{n}.svg" for n in groups.get(name, [])
                         if (pkg / "svgs" / "solid" / f"{n}.svg").exists()), None)
        if svg_path is None:
            missing.append(name)
            continue
        svg = re.sub(r"<!--.*?-->", "", svg_path.read_text(), flags=re.S).strip()
        svg = re.sub(r"\s+", " ", svg)
        rules.append(f'.fa-{name}{{--fa:url("data:image/svg+xml,{quote(svg, safe="/:=,;# ")}")}}')
    if missing:
        sys.exit(f"missing icons: {missing}")
    head = (
        "/* GENERATED by scripts/build_icons.py from Font Awesome Free 6.5.2 (icons: CC BY 4.0,\n"
        "   https://fontawesome.com/license/free). Do not edit; add names to ICONS and regenerate. */\n"
        ".fa,.fas,.far{display:inline-block;width:1em;height:1em;vertical-align:-.125em;flex-shrink:0;"
        "background-color:currentColor;-webkit-mask:var(--fa) center/contain no-repeat;"
        "mask:var(--fa) center/contain no-repeat;font-style:normal}\n"
        ".fa-fw{width:1.25em}.fa-spin{animation:fa-spin 1s linear infinite}"
        "@keyframes fa-spin{to{transform:rotate(360deg)}}\n"
        "@media (prefers-reduced-motion:reduce){.fa-spin{animation-duration:3s}}\n"
    )
    out.write_text(head + "\n".join(rules) + "\n")
    print(f"wrote {out} ({out.stat().st_size} bytes, {len(rules)} icons)")


if __name__ == "__main__":
    main(Path(sys.argv[1]), Path(__file__).resolve().parent.parent / "static" / "css" / "icons.css")
